### ISSUE TITLE
Sprite displaying incorrectly

### ISSUE THREAD

**Issue by ACrazyTown** [barisyild/openfl-animate-atlas#1]
Hi, I'm trying to add this into my project (HaxeFlixel) and I literally copied the tutorial code and copied the ninja girl texture sheet, however parts of the texture atlas are missing and I don't know why since I didn't touch anything apart from the tutorial code.
![image](https://user-images.githubusercontent.com/47027981/167306969-09fcce24-503e-4325-8908-96961c6daf9b.png)

**Comment by barisyild** [comment]
Hi, are you trying to render it as a tile or as a sprite?

**Comment by barisyild** [comment]
I've detected a problem with the C++ target.
I will solve the problem as soon as possible.

**Comment by barisyild** [comment]
#b4116fd

**Comment by barisyild** [comment]
Thank you for reporting.

Problem solved.

b4116fd9fea51d6c4f72687579e23ff60ffbcfe6
